`prefix`
Change the prefix for this bot

`cooldown`
Change the defualt cooldown for commands that use a cooldown

`rm-Building`
remove a building

`reset-buildings`
resets all buildings and refunds the purchaser

`add-building`
adds a building to the economy

`reset-work`
resets the work options to default

`add-work`
adds an option to the work command

`rm-work`
removes an options form the work commands

`view-work`
shows all the optinos for the `work` command

`day`
increments the day paying out all building owner - use sparingly

`buy-roles`
toggles giving roles to users when they buy buildings

`admin-bypass`
toggles admins bypassing the cooldown

`help`
shows this message