`prefix`
Change the prefix for this bot
ex: `prefix !`

`starting-balance`
changes the amount of money new users get on joining
ex: `starting-balance 1000`

`cooldown`
Change the default cooldown for commands that use a cooldown
ex: `cooldown 10`

`add-building`
adds a building to the economy
this is built piece by pice so enter the name first, then the cost, then the generation
ex: `add-building` ... `test` ... `1000` ... `0`

`rm-Building`
remove a building from a given number
ex: `rm-building 1`

`reset-buildings`
resets all buildings and refunds the purchaser

`add-work`
adds an option to the work command
ex: `add-work you work at best buy` 

`rm-work`
removes an options form the work commands from a given number
ex: `rm-work 1`

`reset-work`
resets the work options to default

`view-work`
shows all the options for the `work` command

`day`
increments the day paying out all building owner - use sparingly

`buy-roles`
toggles giving roles to users when they buy buildings
ex: `buy-roles true`

`admin-bypass`
toggles admins bypassing the cooldown
ex: `buy-roles false`

`spam-channel`
sets the channel for the bot to spam into, be default it is the default channel of the server
ex: `spam-channel #spam`

`help`
shows this message